export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';